import { Investigation } from "./types";

export const INVESTIGATIONS: Investigation[] = [
  {
    id: "INV-2041",
    projectId: "MPLADS-KA-1187",
    projectName: "Construction of Community Health Sub-Centre",
    mpName: "Smt. R. Deshmukh",
    constituency: "Belagavi",
    district: "Belagavi",
    state: "Karnataka",
    sector: "Health",
    sanctionedAmount: 3200000,
    utilizedAmount: 2950000,
    riskScore: 91,
    riskLevel: "Critical",
    status: "Under Review",
    assignedTo: "Auditor: A. Sharma",
    flaggedOn: "2026-08-14",
    lastUpdated: "2026-08-20",
    anomalyReasons: [
      { id: "a1", label: "Cost per sq.ft. 340% above district median", detail: "Similar sub-centres in the district average ₹1,850/sq.ft; this project was billed at ₹8,120/sq.ft.", weight: 38 },
      { id: "a2", label: "Zero geotagged photos submitted", detail: "92% of funds marked utilized but no geotagged progress photos exist in the portal, required at 25/50/75/100% stages.", weight: 31 },
      { id: "a3", label: "Contractor flagged in 3 other projects", detail: "Same contractor GSTIN appears in 3 other MPLADS projects flagged for anomalies in the last 30 days.", weight: 22 },
    ],
    evidence: [
      { id: "e1", type: "data", title: "Fund utilization report", description: "Auto-extracted from MPLADS portal utilization certificate.", source: "MoSPI Portal", addedOn: "2026-08-14" },
      { id: "e2", type: "document", title: "Work sanction order", description: "Original sanction order scanned copy.", source: "District Authority", addedOn: "2026-08-14" },
      { id: "e3", type: "satellite", title: "Satellite imagery — site location", description: "No visible construction activity as of latest available pass.", source: "Satellite feed", addedOn: "2026-08-18" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-08-14 09:02", actor: "System", action: "flagged this project automatically", note: "Risk score 91 (Critical)" },
      { id: "t2", timestamp: "2026-08-15 11:20", actor: "A. Sharma", action: "moved the case to \"Under Review\"" },
    ],
    findings: [],
  },
  {
    id: "INV-2038",
    projectId: "MPLADS-KA-1142",
    projectName: "Drinking Water Supply — 4 Villages",
    mpName: "Shri V. Patil",
    constituency: "Chikkodi",
    district: "Belagavi",
    state: "Karnataka",
    sector: "Water & Sanitation",
    sanctionedAmount: 4500000,
    utilizedAmount: 4500000,
    riskScore: 84,
    riskLevel: "Critical",
    status: "Field Verification",
    assignedTo: "Auditor: N. Iyer",
    flaggedOn: "2026-08-10",
    lastUpdated: "2026-08-22",
    anomalyReasons: [
      { id: "a1", label: "Completion certificate predates verification photos", detail: "Completion certificate dated 3 days before the site verification photos were captured.", weight: 40 },
      { id: "a2", label: "Same invoice number reused", detail: "Invoice #INV-7734 appears against two separate MPLADS projects in the same district.", weight: 35 },
      { id: "a3", label: "Sanction-to-completion time 15 days", detail: "Median completion time for comparable works in this district is 210 days.", weight: 25 },
    ],
    evidence: [
      { id: "e1", type: "document", title: "Completion certificate", description: "Signed by executing agency, dated ahead of physical verification.", source: "Executing Agency", addedOn: "2026-08-10" },
      { id: "e2", type: "image", title: "Site verification photos", description: "Photos submitted show incomplete pipeline trenching.", source: "Field team upload", addedOn: "2026-08-19" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-08-10 10:15", actor: "System", action: "flagged this project automatically" },
      { id: "t2", timestamp: "2026-08-12 14:00", actor: "N. Iyer", action: "moved the case to \"Under Review\"" },
      { id: "t3", timestamp: "2026-08-19 09:30", actor: "N. Iyer", action: "moved the case to \"Field Verification\"", note: "Scheduled site visit for 24 Aug" },
    ],
    findings: [
      { id: "f1", author: "N. Iyer", timestamp: "2026-08-19 09:35", note: "Requested physical measurement of pipeline length laid vs. billed quantity." },
    ],
  },
  {
    id: "INV-2035",
    projectId: "MPLADS-KA-1098",
    projectName: "Upgradation of Government Primary School",
    mpName: "Smt. R. Deshmukh",
    constituency: "Belagavi",
    district: "Belagavi",
    state: "Karnataka",
    sector: "Education",
    sanctionedAmount: 1800000,
    utilizedAmount: 1200000,
    riskScore: 67,
    riskLevel: "High",
    status: "New",
    assignedTo: "Unassigned",
    flaggedOn: "2026-08-23",
    lastUpdated: "2026-08-23",
    anomalyReasons: [
      { id: "a1", label: "Vendor GSTIN suspended", detail: "The primary material vendor's GSTIN was suspended 2 weeks before the invoice date.", weight: 45 },
      { id: "a2", label: "Fund utilization delay", detail: "67% of funds utilized against 30% physical progress reported.", weight: 30 },
    ],
    evidence: [
      { id: "e1", type: "data", title: "Vendor GST status check", description: "GSTIN status cross-referenced against GST portal — suspended.", source: "GST Portal API", addedOn: "2026-08-23" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-08-23 08:00", actor: "System", action: "flagged this project automatically" },
    ],
    findings: [],
  },
  {
    id: "INV-2033",
    projectId: "MPLADS-KA-1076",
    projectName: "Solar Street Lighting — Ward 6-9",
    mpName: "Shri V. Patil",
    constituency: "Chikkodi",
    district: "Belagavi",
    state: "Karnataka",
    sector: "Infrastructure",
    sanctionedAmount: 2100000,
    utilizedAmount: 1900000,
    riskScore: 58,
    riskLevel: "High",
    status: "Under Review",
    assignedTo: "Auditor: A. Sharma",
    flaggedOn: "2026-08-11",
    lastUpdated: "2026-08-19",
    anomalyReasons: [
      { id: "a1", label: "GPS coordinates outside constituency boundary", detail: "12 of 40 installed unit geotags fall outside the sanctioned constituency boundary.", weight: 50 },
      { id: "a2", label: "Unit cost 60% above catalogue rate", detail: "Billed ₹18,400/unit vs. empanelled vendor catalogue rate of ₹11,500/unit.", weight: 28 },
    ],
    evidence: [
      { id: "e1", type: "satellite", title: "Geotag boundary overlay", description: "Overlay of submitted geotags against constituency shapefile.", source: "GIS Analysis", addedOn: "2026-08-15" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-08-11 09:00", actor: "System", action: "flagged this project automatically" },
      { id: "t2", timestamp: "2026-08-13 10:00", actor: "A. Sharma", action: "moved the case to \"Under Review\"" },
    ],
    findings: [],
  },
  {
    id: "INV-2028",
    projectId: "MPLADS-KA-0987",
    projectName: "Community Hall Renovation",
    mpName: "Shri K. Rao",
    constituency: "Bagalkot",
    district: "Bagalkot",
    state: "Karnataka",
    sector: "Infrastructure",
    sanctionedAmount: 1500000,
    utilizedAmount: 1500000,
    riskScore: 44,
    riskLevel: "Medium",
    status: "Finding Recorded",
    assignedTo: "Auditor: N. Iyer",
    flaggedOn: "2026-07-28",
    lastUpdated: "2026-08-17",
    anomalyReasons: [
      { id: "a1", label: "Minor cost variance", detail: "Final billed cost 14% above initial sanctioned estimate, within tolerance but flagged for review.", weight: 30 },
      { id: "a2", label: "Delayed geotag submission", detail: "Completion geotags submitted 45 days after physical completion date.", weight: 22 },
    ],
    evidence: [
      { id: "e1", type: "image", title: "Completion photos", description: "Geotagged photos confirm renovation complete and matches scope.", source: "Field team upload", addedOn: "2026-08-16" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-07-28 09:00", actor: "System", action: "flagged this project automatically" },
      { id: "t2", timestamp: "2026-08-02 10:00", actor: "N. Iyer", action: "moved the case to \"Field Verification\"" },
      { id: "t3", timestamp: "2026-08-17 15:40", actor: "N. Iyer", action: "moved the case to \"Finding Recorded\"" },
    ],
    findings: [
      { id: "f1", author: "N. Iyer", timestamp: "2026-08-17 15:42", note: "Site visit confirms work matches sanctioned scope. Cost variance attributable to material price rise, verified against local PWD rate circular.", actionTaken: "No irregularity — recommend closure" },
    ],
  },
  {
    id: "INV-2011",
    projectId: "MPLADS-KA-0854",
    projectName: "Bore-well Installation — Cluster 12",
    mpName: "Smt. R. Deshmukh",
    constituency: "Belagavi",
    district: "Belagavi",
    state: "Karnataka",
    sector: "Water & Sanitation",
    sanctionedAmount: 950000,
    utilizedAmount: 950000,
    riskScore: 22,
    riskLevel: "Low",
    status: "Closed",
    assignedTo: "Auditor: A. Sharma",
    flaggedOn: "2026-07-02",
    lastUpdated: "2026-07-25",
    anomalyReasons: [
      { id: "a1", label: "Minor documentation gap", detail: "One of five completion certificates was uploaded in a non-standard format.", weight: 20 },
    ],
    evidence: [
      { id: "e1", type: "document", title: "Completion certificates", description: "All 5 bore-wells verified complete and functional.", source: "Field team", addedOn: "2026-07-20" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-07-02 09:00", actor: "System", action: "flagged this project automatically" },
      { id: "t2", timestamp: "2026-07-20 12:00", actor: "A. Sharma", action: "moved the case to \"Finding Recorded\"" },
      { id: "t3", timestamp: "2026-07-25 16:00", actor: "A. Sharma", action: "moved the case to \"Closed\"" },
    ],
    findings: [
      { id: "f1", author: "A. Sharma", timestamp: "2026-07-25 15:55", note: "All bore-wells physically verified and operational. Documentation format corrected.", actionTaken: "Case closed — no irregularity" },
    ],
  },
  {
    id: "INV-2005",
    projectId: "MPLADS-KA-0801",
    projectName: "Road Widening — NH Link Road",
    mpName: "Shri K. Rao",
    constituency: "Bagalkot",
    district: "Bagalkot",
    state: "Karnataka",
    sector: "Infrastructure",
    sanctionedAmount: 8500000,
    utilizedAmount: 8100000,
    riskScore: 96,
    riskLevel: "Critical",
    status: "Escalated",
    assignedTo: "Auditor: N. Iyer",
    flaggedOn: "2026-06-18",
    lastUpdated: "2026-08-05",
    anomalyReasons: [
      { id: "a1", label: "Quantity billed exceeds physical measurement by 3.2x", detail: "Road length billed as 4.2 km; field measurement confirms only 1.3 km constructed.", weight: 55 },
      { id: "a2", label: "Contractor linked to blacklisted entity", detail: "Executing contractor shares a registered director with a firm blacklisted by CPWD in 2025.", weight: 45 },
    ],
    evidence: [
      { id: "e1", type: "satellite", title: "Before/after satellite comparison", description: "Confirms construction on only ~1.3 km of the billed 4.2 km stretch.", source: "Satellite feed", addedOn: "2026-07-10" },
      { id: "e2", type: "data", title: "Contractor ownership cross-check", description: "MCA21 director records matched against CPWD blacklist database.", source: "MCA21 + CPWD", addedOn: "2026-07-15" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-06-18 09:00", actor: "System", action: "flagged this project automatically" },
      { id: "t2", timestamp: "2026-07-10 11:00", actor: "N. Iyer", action: "moved the case to \"Field Verification\"" },
      { id: "t3", timestamp: "2026-08-05 10:00", actor: "N. Iyer", action: "moved the case to \"Escalated\"", note: "Referred to CVC for further action" },
    ],
    findings: [
      { id: "f1", author: "N. Iyer", timestamp: "2026-08-05 09:50", note: "Confirmed large-scale quantity misreporting and contractor blacklist linkage. Case exceeds departmental audit scope.", actionTaken: "Escalated to CVC/CBI for investigation" },
    ],
  },
];